// Canonical Gallery grouping data — pure data, no React/Next imports so the
// client-catalog generator and Node consistency gates consume the same ordered
// component universe as the scrollable Gallery browser.

export interface GalleryCatalogItem {
  label: string
  slug: string
}

export interface GalleryCatalogGroup {
  group: string
  items: GalleryCatalogItem[]
}

export const GALLERY_GROUPS: GalleryCatalogGroup[] = [
  { group: "Foundations", items: [
    { label: "Color Tokens", slug: "colors" },
    { label: "Typography", slug: "type" },
    { label: "Spacing & Radii", slug: "spacing" },
    { label: "Brand & Mark", slug: "brand" },
    { label: "Direction", slug: "direction" },
  ]},
  { group: "Controls", items: [
    { label: "Buttons", slug: "buttons" },
    { label: "Button Group", slug: "button-group" },
    { label: "Badges", slug: "badges" },
    { label: "Toggle Switch", slug: "switch" },
    { label: "Toggle", slug: "toggle" },
    { label: "Toggle Group", slug: "toggle-group" },
    { label: "Avatar", slug: "avatar" },
    { label: "Progress", slug: "progress" },
    { label: "Spinner", slug: "spinner" },
    { label: "Separator", slug: "separator" },
    { label: "Toolbar", slug: "toolbar" },
    { label: "Kbd", slug: "kbd" },
  ]},
  { group: "Form Elements", items: [
    { label: "Inputs & Selects", slug: "forms" },
    { label: "Input", slug: "input" },
    { label: "Field", slug: "field" },
    { label: "Label", slug: "label" },
    { label: "Input Group", slug: "input-group" },
    { label: "Input OTP", slug: "input-otp" },
    { label: "Native Select", slug: "native-select" },
    { label: "Select", slug: "select" },
    { label: "Combobox", slug: "combobox" },
    { label: "Checkbox & Radio", slug: "checkboxes" },
    { label: "Radio Group", slug: "radio-group" },
    { label: "Slider", slug: "slider" },
    { label: "Number Input", slug: "number-input" },
    { label: "Textarea", slug: "textarea" },
    { label: "Calendar", slug: "calendar" },
    { label: "Date Picker", slug: "date-picker" },
    { label: "Tabs & Pills", slug: "tabs" },
  ]},
  { group: "Feedback", items: [
    { label: "Alert", slug: "alert" },
    { label: "Banners", slug: "banners" },
    { label: "Callout", slug: "callout" },
    { label: "Toasts", slug: "toasts" },
    { label: "Sonner", slug: "sonner" },
    { label: "Tooltip", slug: "tooltip" },
    { label: "Empty States", slug: "empty" },
    { label: "Skeleton", slug: "skeleton" },
    { label: "Status Indicator", slug: "status-indicator" },
    { label: "Shimmer", slug: "shimmer" },
    { label: "Confirmation", slug: "confirmation" },
  ]},
  { group: "Navigation", items: [
    { label: "Breadcrumb", slug: "breadcrumb" },
    { label: "Pagination", slug: "pagination" },
    { label: "Command", slug: "command" },
    { label: "Navigation Menu", slug: "navigation-menu" },
    { label: "Menubar", slug: "menubar" },
  ]},
  { group: "Data", items: [
    { label: "Stat Cards", slug: "stats" },
    { label: "Tables", slug: "tables" },
    { label: "Data Table", slug: "data-table" },
    { label: "Filter Bars", slug: "filters" },
    { label: "Timeline", slug: "timeline" },
    { label: "Description List", slug: "description-list" },
    { label: "Search Results", slug: "search-results" },
    { label: "Listbox", slug: "listbox" },
    { label: "Marketplace", slug: "marketplace" },
  ]},
  { group: "Overlays", items: [
    { label: "Modal & Dialog", slug: "modals" },
    { label: "Alert Dialog", slug: "alert-dialog" },
    { label: "Accordion", slug: "accordion" },
    { label: "Collapsible", slug: "collapsible" },
    { label: "Dropdowns", slug: "dropdowns" },
    { label: "Context Menu", slug: "context-menu" },
    { label: "Popover", slug: "popover" },
    { label: "Hover Card", slug: "hover-card" },
    { label: "Sheet", slug: "sheet" },
    { label: "Drawer", slug: "drawer" },
    { label: "Share Dialog", slug: "share-dialog" },
  ]},
  { group: "Chat Primitives", items: [
    { label: "Interactive Chat", slug: "chat-block" },
    { label: "Message Scroller", slug: "message-scroller" },
    { label: "Message", slug: "message-primitive" },
    { label: "Bubble", slug: "bubble" },
    { label: "Attachment", slug: "chat-attachment" },
    { label: "Marker", slug: "marker" },
  ]},
  { group: "Chat & AI", items: [
    { label: "Prompt Input", slug: "prompt-input" },
    { label: "AI Elements", slug: "ai-elements" },
    { label: "Message", slug: "message" },
    { label: "Conversation", slug: "conversation" },
    { label: "Model Selector", slug: "model-selector" },
    { label: "Persona", slug: "persona" },
    { label: "Open in Chat", slug: "open-in-chat" },
    { label: "Reasoning", slug: "reasoning" },
    { label: "Tool Calls", slug: "tool-calls" },
    { label: "Tool", slug: "tool" },
    { label: "Thinking", slug: "thinking" },
    { label: "Chain of Thought", slug: "chain-of-thought" },
    { label: "Plan", slug: "plan" },
    { label: "Task", slug: "task" },
    { label: "Queue", slug: "queue" },
    { label: "Suggestion", slug: "suggestion" },
    { label: "Code Block", slug: "code-block" },
    { label: "Artifact", slug: "artifact" },
    { label: "Terminal", slug: "terminal" },
    { label: "Permission Prompt", slug: "permission-prompt" },
    { label: "Ask User Question", slug: "ask-user-question" },
    { label: "Permissions Config", slug: "permissions-dropdown" },
    { label: "Command Palette", slug: "command-palette" },
    { label: "Sidebar", slug: "sidebar" },
  ]},
  { group: "Runtime & Execution", items: [
    { label: "Agent", slug: "agent" },
    { label: "Checkpoint", slug: "checkpoint" },
    { label: "Commit", slug: "commit" },
    { label: "Context Panel", slug: "context" },
    { label: "Environment Variables", slug: "environment-variables" },
    { label: "Package Info", slug: "package-info" },
    { label: "Schema Display", slug: "schema-display" },
    { label: "Sandbox", slug: "sandbox" },
    { label: "Snippet", slug: "snippet" },
    { label: "JSX Preview", slug: "jsx-preview" },
    { label: "Stack Trace", slug: "stack-trace" },
    { label: "Test Results", slug: "test-results" },
    { label: "Panel", slug: "panel" },
    { label: "Control Strip", slug: "controls" },
    { label: "Canvas", slug: "canvas" },
    { label: "Connection", slug: "connection" },
    { label: "Edge", slug: "edge" },
    { label: "Node", slug: "node" },
  ]},
  { group: "Media & Voice", items: [
    { label: "Audio Player", slug: "audio-player" },
    { label: "Mic Selector", slug: "mic-selector" },
    { label: "Speech Input", slug: "speech-input" },
    { label: "Transcription", slug: "transcription" },
    { label: "Voice Selector", slug: "voice-selector" },
  ]},
  { group: "Content", items: [
    { label: "Attachment Chip", slug: "attachment" },
    { label: "AI Attachments", slug: "attachments" },
    { label: "Sources", slug: "sources" },
    { label: "Inline Citation", slug: "inline-citation" },
    { label: "File Picker", slug: "file-picker" },
    { label: "File Tree", slug: "file-tree" },
    { label: "Code Editor", slug: "code-editor" },
    { label: "Code Workspace", slug: "code-workspace" },
    { label: "Web Preview", slug: "web-preview" },
    { label: "Aspect Ratio", slug: "aspect-ratio" },
    { label: "Card", slug: "card" },
    { label: "Carousel", slug: "carousel" },
    { label: "Chart", slug: "chart" },
    { label: "Image", slug: "image" },
    { label: "Item", slug: "item" },
    { label: "Resizable Panels", slug: "resizable-panels" },
    { label: "Scroll Area", slug: "scroll-area" },
  ]},
  { group: "Auth & Errors", items: [
    { label: "Login", slug: "login" },
    { label: "OAuth Flow", slug: "oauth" },
    { label: "Error Pages", slug: "error-pages" },
  ]},
  { group: "Themes", items: [
    { label: "Light Mode", slug: "lightmode" },
  ]},
  { group: "AI Elements (new)", items: [
    { label: "Action", slug: "action" },
    { label: "Actions", slug: "actions" },
    { label: "AiImageGrid", slug: "ai-image-grid" },
    { label: "Branch", slug: "branch" },
    { label: "Loader", slug: "loader" },
    { label: "MessageAvatar", slug: "message-avatar" },
    { label: "MessageContent", slug: "message-content" },
    { label: "Response", slug: "response" },
    { label: "Source", slug: "source" },
  ]},
  { group: "Aurora Extensions", items: [
    { label: "ChatMessage", slug: "chat-message" },
    { label: "ChatSidebar", slug: "chat-sidebar" },
    { label: "ColorPicker", slug: "color-picker" },
    { label: "ComponentCard", slug: "component-card" },
    { label: "CopyButton", slug: "copy-button" },
    { label: "MultiSelect", slug: "multi-select" },
    { label: "OperationIcon", slug: "operation-icon" },
    { label: "ProgressRing", slug: "progress-ring" },
    { label: "RangeSlider", slug: "range-slider" },
    { label: "Rating", slug: "rating" },
    { label: "Segmented", slug: "segmented" },
    { label: "Spotlight", slug: "spotlight" },
    { label: "StatusDot", slug: "status-dot" },
    { label: "Stepper", slug: "stepper" },
    { label: "TagInput", slug: "tag-input" },
  ]},
]

